/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kesequl.app;

import com.kesequl.app.entity.EventVoting;
import com.kesequl.app.entity.NominasiTeam;
import com.kesequl.app.entity.Siswa;
import com.kesequl.app.entity.User;
import com.kesequl.app.network.Client;
import com.kesequl.app.network.KesequlHttpCallback;
import com.kesequl.app.network.KesequlHttpRequest;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.IntSupplier;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user65
 */
public final class KelolaTeamVoting extends javax.swing.JFrame {
    private static final long serialVersionUID = 374267292223931376L;
    
    private final User user;

    private final EventVoting eventVoting;
    private Runnable parentRunnable;
    
    private final List<NominasiTeam> listTeam = new ArrayList<>();
    private boolean editMode = false;
    private NominasiTeam editEntity;
    
    private int idKetua = -1;
    private int idWakil = -1;
    
    private Siswa selectedSiswa;
    
    /**
     * Creates new form KelolaDetailVoting
     * @param user
     * @param eventVoting
     * @param parentRunnable
     */
    public KelolaTeamVoting(User user, EventVoting eventVoting, Runnable parentRunnable) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getClassLoader().getResource("image/icon_kesequl.png")).getImage());
        
        framePilihSiswa.setSize(420, 240);
        
        this.eventVoting = eventVoting;
        this.parentRunnable = parentRunnable;
        
        this.user = user;
        
        lblNamaEvent.setText(eventVoting.getNama());
        
        
        btnRefreshActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framePilihSiswa = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblNamaSiswa = new javax.swing.JLabel();
        lblKelasSiswa = new javax.swing.JLabel();
        lblGenderSiswa = new javax.swing.JLabel();
        btnPilihSiswa = new javax.swing.JButton();
        btnBatalSiswa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaTeam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCariKetua = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCariWakil = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtVisi = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMisi = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNamaEvent = new javax.swing.JLabel();

        framePilihSiswa.setType(java.awt.Window.Type.UTILITY);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Username");

        jLabel17.setText(":");

        btnCari.setText("Cari");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Nama");

        jLabel10.setText("Kelas");

        jLabel11.setText("Gender");

        jLabel12.setText(":");

        jLabel14.setText(":");

        jLabel15.setText(":");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNamaSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKelasSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGenderSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(lblNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel14))
                    .addComponent(lblKelasSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel15))
                    .addComponent(lblGenderSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPilihSiswa.setText("Pilih");
        btnPilihSiswa.setEnabled(false);

        btnBatalSiswa.setText("Batalkan");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsername))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(btnPilihSiswa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatalSiswa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCari))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCari)
                .addGap(1, 1, 1)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPilihSiswa)
                    .addComponent(btnBatalSiswa))
                .addContainerGap())
        );

        javax.swing.GroupLayout framePilihSiswaLayout = new javax.swing.GroupLayout(framePilihSiswa.getContentPane());
        framePilihSiswa.getContentPane().setLayout(framePilihSiswaLayout);
        framePilihSiswaLayout.setHorizontalGroup(
            framePilihSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        framePilihSiswaLayout.setVerticalGroup(
            framePilihSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Team", "Ketua", "Wakil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nama Team");

        jLabel2.setText(":");

        jLabel5.setText("Ketua");

        jLabel6.setText(":");

        btnCariKetua.setText("-- Pilih Ketua --");
        btnCariKetua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariKetuaActionPerformed(evt);
            }
        });

        jLabel7.setText("Wakil");

        jLabel8.setText(":");

        btnCariWakil.setText("-- Pilih Wakil --");
        btnCariWakil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariWakilActionPerformed(evt);
            }
        });

        jLabel16.setText("Visi");

        jLabel18.setText(":");

        txtVisi.setColumns(20);
        txtVisi.setRows(5);
        jScrollPane2.setViewportView(txtVisi);

        txtMisi.setColumns(20);
        txtMisi.setRows(5);
        jScrollPane3.setViewportView(txtMisi);

        jLabel19.setText("Misi");

        jLabel20.setText(":");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNamaTeam))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariKetua))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariWakil)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(btnCariKetua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(btnCariWakil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel18))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Event");

        jLabel4.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambah))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblNamaEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lblNamaEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnRefresh))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        btnRefresh.setEnabled(false);
        
        KesequlHttpRequest req = new KesequlHttpRequest(KesequlHttpRequest.Method.GET);
        req.setUrl("voting/team?as=admin&token=" + user.getToken() + "&id_event_voting=" + eventVoting.getIdEventVoting());
        Client.executeConnectionList(req, NominasiTeam.class, new KesequlHttpCallback<List<NominasiTeam>>() {
            @Override
            public void onSuccess(int status, String pesan, List<NominasiTeam> data) {
                if (!Client.isTokenExpired(KelolaTeamVoting.this, status, user)) {
                    if (status == 1) {
                        DefaultTableModel model = (DefaultTableModel) table.getModel();
                        model.setNumRows(0);

                        listTeam.clear();
                        listTeam.addAll(data);

                        if (listTeam != null) {
                            listTeam.forEach(team -> {
                                model.addRow(new Object[] {
                                    team.getNama(),
                                    team.getNamaKetua() + " ( " + team.getKelasKetua() + " )",
                                    team.getNamaWakil() + " ( " + team.getKelasWakil() + " )"
                                });
                            });
                        }
                        if (listTeam.size()<1)
                            model.removeRow(0);
                        table.setModel(model);
                    }
                }
                
            }

            @Override
            public void onFailed(Exception ex) {
                JOptionPane.showMessageDialog(KelolaTeamVoting.this, ex.getMessage());
            }

            @Override
            public void onDone() {
                if (parentRunnable != null) {
                    parentRunnable.run();
                    parentRunnable = null;
                }
                
                btnRefresh.setEnabled(true);
            }
        });
        
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCariKetuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariKetuaActionPerformed
        showInputSiswa("Ketua", (siswa) -> {
            idKetua = siswa.getIdSiswa();
            btnCariKetua.setText(siswa.getNama() + " ( " + siswa.getKelas() + " " + siswa.getJurusan().getNama() + " " + siswa.getIndexJurusan() + " )");
        });
    }//GEN-LAST:event_btnCariKetuaActionPerformed

    private void btnCariWakilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariWakilActionPerformed
        showInputSiswa("Wakil", (siswa) -> {
            idWakil = siswa.getIdSiswa();
            btnCariWakil.setText(siswa.getNama() + " ( " + siswa.getKelas() + " " + siswa.getJurusan().getNama() + " " + siswa.getIndexJurusan() + " )");
        });
    }//GEN-LAST:event_btnCariWakilActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String namaTeam = txtNamaTeam.getText().trim();
        String visi = txtVisi.getText().trim();
        String misi = txtMisi.getText().trim();
        
        if (namaTeam.isEmpty() || visi.isEmpty() || misi.isEmpty() || idKetua == -1 || idWakil == -1) {
            JOptionPane.showMessageDialog(this, "Input tidak boleh kosong");
            return;
        }
        
        KesequlHttpRequest req = new KesequlHttpRequest(KesequlHttpRequest.Method.POST);
        req.setUrl("voting/tambahteam?token=" + user.getToken());
        req.setVal(
                "id_event_voting=" + eventVoting.getIdEventVoting() + 
                "&nama=" + namaTeam + 
                "&id_ketua=" + idKetua +
                "&id_wakil=" + idWakil +
                "&visi=" + visi +
                "&misi=" + misi
        );
        Client.executeConnection(req, null, new KesequlHttpCallback() {
            @Override
            public void onPrepare() {
                btnTambah.setEnabled(false);
            }
            @Override
            public void onSuccess(int status, String pesan, Object data) {
                if (!Client.isTokenExpired(KelolaTeamVoting.this, status, user)) {
                    if (status == 1) {
                        btnTambah.setEnabled(true);
                        btnRefreshActionPerformed(evt);
                        
                        txtNamaTeam.setText("");
                        txtVisi.setText("");
                        txtMisi.setText("");
                        idKetua = -1;
                        idWakil = -1;
                        btnCariKetua.setText("-- Pilih Ketua --");
                        btnCariWakil.setText("-- Pilih Wakil --");
                    }
                    
                    JOptionPane.showMessageDialog(KelolaTeamVoting.this, pesan);
                }
            }

            @Override
            public void onFailed(Exception ex) {
                JOptionPane.showMessageDialog(KelolaTeamVoting.this, ex);
            }
            
            @Override
            public void onDone() {
                btnTambah.setEnabled(true);
                btnRefreshActionPerformed(evt);
            }
        });
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (!editMode) {
            int row = table.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Mau Diedit");
                return;
            }
            
            NominasiTeam teamS = listTeam.get(row);

            editMode = true;
            editEntity = teamS;
            
            txtNamaTeam.setText(teamS.getNama());
            txtVisi.setText(teamS.getVisi());
            txtMisi.setText(teamS.getMisi());
            idKetua = teamS.getIdKetua();
            idWakil = teamS.getIdWakil();
            btnCariKetua.setText(teamS.getNamaKetua() + " ( " + teamS.getKelasKetua() + " )");
            btnCariWakil.setText(teamS.getNamaWakil() + " ( " + teamS.getKelasWakil() + " )");
        } else {
            String namaTeam = txtNamaTeam.getText().trim();
            String visi = txtVisi.getText().trim();
            String misi = txtMisi.getText().trim();

            if (namaTeam.isEmpty() || visi.isEmpty() || misi.isEmpty() || idKetua == -1 || idWakil == -1) {
                JOptionPane.showMessageDialog(this, "Input tidak boleh kosong");
                return;
            }
            
            KesequlHttpRequest req = new KesequlHttpRequest(KesequlHttpRequest.Method.POST);
            req.setUrl("voting/editteam?token=" + user.getToken());
            req.setVal(
                "id_team=" + editEntity.getIdNominasiTeam() +
                "&nama=" + namaTeam + 
                "&id_ketua=" + idKetua +
                "&id_wakil=" + idWakil +
                "&visi=" + visi +
                "&misi=" + misi
            );
            
            Client.executeConnection(req, null, new KesequlHttpCallback() {
                @Override
                public void onSuccess(int status, String pesan, Object data) {
                    if (!Client.isTokenExpired(KelolaTeamVoting.this, status, user)) {
                        if (status == 1) {
                            editMode = false;
                            editEntity = null;
                            
                            txtNamaTeam.setText("");
                            txtVisi.setText("");
                            txtMisi.setText("");
                            idKetua = -1;
                            idWakil = -1;
                            btnCariKetua.setText("-- Pilih Ketua --");
                            btnCariWakil.setText("-- Pilih Wakil --");
                        }
                        JOptionPane.showMessageDialog(KelolaTeamVoting.this, pesan);
                    }
                }

                @Override
                public void onFailed(Exception ex) {
                    JOptionPane.showMessageDialog(KelolaTeamVoting.this, ex.getMessage());
                }
                
                @Override
                public void onDone() {
                    btnRefresh.setEnabled(!editMode);
                    btnTambah.setEnabled(!editMode);
                    btnEdit.setText(!editMode ? "Edit" : "Terapkan");
                    btnHapus.setEnabled(!editMode);
                    
                    btnRefreshActionPerformed(evt);
                }
            });
        }
        
        btnRefresh.setEnabled(!editMode);
        btnTambah.setEnabled(!editMode);
        btnEdit.setText(!editMode ? "Edit" : "Terapkan");
        btnHapus.setEnabled(!editMode);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = table.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Mau Diedit");
            return;
        }
        
        NominasiTeam teamS = listTeam.get(row);
        
        if (JOptionPane.showConfirmDialog(this, "Yakin ingin dihapus ?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            btnHapus.setEnabled(false);
            KesequlHttpRequest req = new KesequlHttpRequest(KesequlHttpRequest.Method.POST);
            req.setUrl("voting/hapusteam?token=" + user.getToken());
            req.setVal("id_team=" + teamS.getIdNominasiTeam());
            
            Client.executeConnection(req, null, new KesequlHttpCallback() {
                @Override
                public void onSuccess(int status, String pesan, Object data) {
                    if (!Client.isTokenExpired(KelolaTeamVoting.this, status, user))
                        JOptionPane.showMessageDialog(KelolaTeamVoting.this, pesan);
                }

                @Override
                public void onFailed(Exception ex) {
                    JOptionPane.showMessageDialog(KelolaTeamVoting.this, ex.getMessage());
                }
                
                @Override
                public void onDone() {
                    btnHapus.setEnabled(true);
                    btnRefreshActionPerformed(evt);
                }
            });
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    public void showInputSiswa(String title, Consumer<Siswa> consumer) {
        if (framePilihSiswa.isShowing()) {
            JOptionPane.showMessageDialog(this, "Input dulu yang satunya");
            framePilihSiswa.requestFocus();
            return;
        }
        
        framePilihSiswa.setTitle(title);
        framePilihSiswa.setLocationRelativeTo(this);
        
        btnCari.addActionListener((e) -> {
            String username = txtUsername.getText().trim();
            
            if (username.isEmpty()) {
                JOptionPane.showMessageDialog(framePilihSiswa, "Input tidak boleh kosong");
                return;
            }

            txtUsername.setText("");
            
            KesequlHttpRequest req = new KesequlHttpRequest(KesequlHttpRequest.Method.GET);
            req.setUrl("siswa/datauser");
            req.setVal("token=" + user.getToken() + "&username=" + username);
            Client.executeConnection(req, Siswa.class, new KesequlHttpCallback<Siswa>() {
                @Override
                public void onPrepare() {
                    btnCari.setEnabled(false);
                }
                
                @Override
                public void onSuccess(int status, String pesan, Siswa data) {
                    if (!Client.isTokenExpired(framePilihSiswa, status, user)) {
                        if (status == 1) {
                            selectedSiswa = data;
                            lblNamaSiswa.setText(data.getNama());
                            lblKelasSiswa.setText(data.getKelas() + " " + data.getJurusan().getNama() + " " + data.getIndexJurusan());
                            lblGenderSiswa.setText(data.getGender() == 'L' ? "Laki-laki" : "Perempuan");
                            btnPilihSiswa.setEnabled(true);
                        } else {
                            JOptionPane.showMessageDialog(framePilihSiswa, pesan);
                        }
                    }
                }

                @Override
                public void onFailed(Exception ex) {
                    JOptionPane.showMessageDialog(framePilihSiswa, ex.getMessage());
                }

                @Override
                public void onDone() {
                    btnCari.setEnabled(true);
                }
            });
        });
        btnPilihSiswa.addActionListener((e) -> {
            framePilihSiswa.setVisible(false);
            if (selectedSiswa != null) {
                consumer.accept(selectedSiswa);
                selectedSiswa = null;
            }
            
            requestFocus();
            btnPilihSiswa.setEnabled(false);
        });
        btnBatalSiswa.addActionListener((e) -> {
            framePilihSiswa.setVisible(false);
            selectedSiswa = null;
            requestFocus();
            btnBatalSiswa.setEnabled(false);
        });
        
        txtUsername.setText("");
        lblNamaSiswa.setText("");
        lblKelasSiswa.setText("");
        lblGenderSiswa.setText("");
        btnPilihSiswa.setEnabled(false);
        
        framePilihSiswa.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalSiswa;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCariKetua;
    private javax.swing.JButton btnCariWakil;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPilihSiswa;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JFrame framePilihSiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblGenderSiswa;
    private javax.swing.JLabel lblKelasSiswa;
    private javax.swing.JLabel lblNamaEvent;
    private javax.swing.JLabel lblNamaSiswa;
    private javax.swing.JTable table;
    private javax.swing.JTextArea txtMisi;
    private javax.swing.JTextField txtNamaTeam;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextArea txtVisi;
    // End of variables declaration//GEN-END:variables
}
