/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kesequl.app;

import com.kesequl.app.entity.Admin;
import com.kesequl.app.entity.Jurusan;
import com.kesequl.app.entity.Siswa;
import com.kesequl.app.entity.User;
import com.kesequl.app.network.Client;
import com.kesequl.app.network.KesequlHttpCallback;
import com.kesequl.app.network.KesequlHttpRequest;
import java.io.File;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;

/**
 *
 * @author user65
 */
public final class KelolaSiswa extends javax.swing.JFrame {

    private static final long serialVersionUID = -1315015601237883041L;

    private final User user;
    private final Admin admin;
    
    private final List<Siswa> listSiswa = new ArrayList<>();
    private final List<Jurusan> listJurusan = new ArrayList<>();
    
    private boolean editMode = false;
    private Siswa editEntity = null;
    
    private Runnable parentRunnable;
    
    /**
     * Creates new form TambahSiswa
     * @param user
     * @param admin
     */
    public KelolaSiswa(User user, Admin admin, Runnable parentRunnable) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getClassLoader().getResource("image/icon_kesequl.png")).getImage());
        
        this.user = user;
        this.admin = admin;
        this.parentRunnable = parentRunnable;
        
        chooserImage.setAcceptAllFileFilterUsed(false);
        chooserImage.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("File Gambar", "jpg", "png", "jpeg"));
        
        btnRefreshActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb_jk = new javax.swing.ButtonGroup();
        chooserImage = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNisn = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        rbL = new javax.swing.JRadioButton();
        rbP = new javax.swing.JRadioButton();
        txtLahir = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboJurusan = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        spnKelas = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        spnIndexJurusan = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtGambar = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBan = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();

        chooserImage.setFileHidingEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Siswa");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NISN", "Username", "Email", "Nama", "Gender", "Tanggal Lahir", "Kelas", "Jurusan", "Index Jurusan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nama");

        jLabel7.setText("NISN");

        jLabel9.setText("Gender");

        jLabel11.setText("Tanggal Lahir");

        jLabel2.setText(":");

        jLabel3.setText(":");

        jLabel5.setText(":");

        jLabel6.setText(":");

        txtNisn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNisnKeyTyped(evt);
            }
        });

        rbL.setBackground(new java.awt.Color(255, 255, 255));
        rb_jk.add(rbL);
        rbL.setSelected(true);
        rbL.setText("L");

        rbP.setBackground(new java.awt.Color(255, 255, 255));
        rb_jk.add(rbP);
        rbP.setText("P");

        txtLahir.setDateFormatString("dd-MM-yyyy");

        jLabel4.setText("Jurusan");

        jLabel8.setText(":");

        jLabel10.setText("Kelas");

        jLabel12.setText(":");

        spnKelas.setModel(new javax.swing.SpinnerNumberModel(10, 10, 12, 1));

        jLabel14.setText("Index Jurusan");

        spnIndexJurusan.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        jLabel16.setText("Email");

        jLabel19.setText(":");

        jLabel20.setText("Foto Profile");

        jLabel21.setText(":");

        jButton1.setText("Gambar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtGambar.setEditable(false);

        jLabel22.setText(":");

        jButton2.setText("Lihat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNisn)
                                    .addComponent(txtNama)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGambar))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spnKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(rbL)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(rbP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(txtLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                                    .addComponent(comboJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel22)
                                                .addGap(18, 18, 18)
                                                .addComponent(spnIndexJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(txtNisn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(rbL)
                    .addComponent(rbP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(spnKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(comboJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(spnIndexJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnBan.setText("Ban");
        btnBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanActionPerformed(evt);
            }
        });

        btnNext.setText("->");

        btnPrev.setText("<-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBan)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTambah))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPrev)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnNext)
                    .addComponent(btnPrev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnBan))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        btnRefresh.setEnabled(false);
                
        Client.executeForResultList(true, null, new KesequlHttpRequest(KesequlHttpRequest.Method.GET, "jurusan/all"), Jurusan.class, new KesequlHttpCallback<Jurusan>() {
            DefaultComboBoxModel model;
            @Override
            public void onPrepare() {
                model = (DefaultComboBoxModel) comboJurusan.getModel();
                model.removeAllElements();

                listJurusan.clear();
            }
            
            @Override
            public void onSuccess(int status, String pesan, Jurusan data) {
                if (data != null) {
                    listJurusan.add(data);
                    
                    model.addElement(data.getNama());
                }
            }

            @Override
            public void onFailed(Exception ex) {
                JOptionPane.showMessageDialog(KelolaSiswa.this, ex.getMessage());
            }

            @Override
            public void onDone() {
                comboJurusan.setModel(model);
            } 
        });
        
        KesequlHttpRequest req = new KesequlHttpRequest(KesequlHttpRequest.Method.GET);
        req.setUrl("admin/allsiswa?token=" + user.getToken());
        
        Client.executeForResultList(true, null, req, Siswa.class, new KesequlHttpCallback<Siswa>() {
            private DefaultTableModel model;
            
            @Override
            public void onPrepare() {
                btnRefresh.setEnabled(false);
                
                model = (DefaultTableModel) table.getModel();
                model.setRowCount(0);

                listSiswa.clear();
            }
            
            @Override
            public void onSuccess(int status, String pesan, Siswa data) {
                if (data != null) {
                    listSiswa.add(data);
                    model.addRow(new Object[] {
                        data.getNisn(),
                        data.getUser().getUsername(),
                        data.getUser().getEmail(),
                        data.getNama(),
                        data.getGender() == 'L' ? "Laki-Laki" : "Perempuan",
                        data.getTtl().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")),
                        String.valueOf(data.getKelas()),
                        data.getJurusan().getNama(),
                        data.getIndexJurusan()
                    });
                    
                    table.repaint();
                }
            }

            @Override
            public void onFailed(Exception ex) {
                JOptionPane.showMessageDialog(KelolaSiswa.this, ex.getMessage());
            }
            
            @Override
            public void onDone() {
                if (parentRunnable != null) {
                    parentRunnable.run();
                    parentRunnable = null;
                }
                
                table.setModel(model);
                
                btnRefresh.setEnabled(true);
            }
        });
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtNisnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNisnKeyTyped
        if (!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtNisnKeyTyped

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String nisn = txtNisn.getText().trim();
        String nama = txtNama.getText().trim();
        String gender = rbL.isSelected() ? "L" : "P";
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal_lahir = txtLahir.getDate() != null ? dateFormat.format(txtLahir.getDate()) : "";
        String kelas = String.valueOf(spnKelas.getValue()).trim();
        Jurusan jurusan = null;
        for (Jurusan j : listJurusan) {
            if (j.getNama().equals(String.valueOf(comboJurusan.getSelectedItem()))) {
                jurusan = j;
                break;
            }
        }
        String index_jurusan = String.valueOf(spnIndexJurusan.getValue()).trim();
        String email = txtEmail.getText().trim();
        
        if (nisn.isEmpty() || nama.isEmpty() || gender.isEmpty() || tanggal_lahir.isEmpty() || email.isEmpty() || kelas.isEmpty() || jurusan == null || index_jurusan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak boleh ada inputan yang kosong");
            return;
        }
        
        String locGambar = txtGambar.getText().trim();
        
        MultipartEntityBuilder entityBuilder = MultipartEntityBuilder.create()
                .addTextBody("nisn", nisn)
                .addTextBody("nama", nama)
                .addTextBody("gender", gender)
                .addTextBody("tanggal_lahir", tanggal_lahir)
                .addTextBody("email", email)
                .addTextBody("kelas", kelas)
                .addTextBody("id_jurusan", String.valueOf(jurusan.getIdJurusan()))
                .addTextBody("index_jurusan", String.valueOf(index_jurusan));
        
        if (!locGambar.isEmpty()) {
            File file = new File(txtGambar.getText());
            
            entityBuilder.addBinaryBody("gambar", file);
        }
        
        KesequlHttpRequest req = new KesequlHttpRequest(KesequlHttpRequest.Method.POST);
        req.setUrl("siswa/tambahsiswa?token=" + user.getToken());
        
        Client.executeForResult(true, entityBuilder.build(), req, null, new KesequlHttpCallback() {
            @Override
            public void onPrepare() {
                btnTambah.setEnabled(false);
            }
            
            @Override
            public void onSuccess(int status, String pesan, Object data) {
                if (!Client.isTokenExpired(KelolaSiswa.this, status, user)) {
                    if (status == 1) {
                        btnTambah.setEnabled(true);
                        btnRefreshActionPerformed(evt);
                        
                        txtNisn.setText("");
                        txtNama.setText("");
                        rbL.setSelected(true);
                        txtLahir.setDate(null);
                        txtEmail.setText("");
                        spnKelas.setValue(10);
                        spnIndexJurusan.setValue(1);
                    }
                    
                    JOptionPane.showMessageDialog(KelolaSiswa.this, pesan);
                }
            }

            @Override
            public void onFailed(Exception ex) {
                JOptionPane.showMessageDialog(KelolaSiswa.this, ex);
            }
            
            @Override
            public void onDone() {
                btnTambah.setEnabled(true);
                btnRefreshActionPerformed(evt);
            }
        });
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (!editMode) {
            int row = table.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Mau Diedit");
                return;
            }
            
            Siswa siswaS = listSiswa.get(row);

            editMode = true;
            editEntity = siswaS;
            
            txtNama.setText(siswaS.getNama());
            txtNisn.setText(String.valueOf(siswaS.getNisn()));
            // Harus dikurangi 1900, karena library Date otomatis menambahkan 1900
            txtLahir.setDate(new Date(siswaS.getTtl().getYear() - 1900, siswaS.getTtl().getMonthValue(), siswaS.getTtl().getDayOfMonth()));
            rbL.setSelected(siswaS.getGender() == 'L');
            txtEmail.setText(siswaS.getUser().getEmail());
            spnKelas.setValue(siswaS.getKelas());
            comboJurusan.setSelectedItem(siswaS.getJurusan().getNama());
            spnIndexJurusan.setValue(siswaS.getIndexJurusan());
        } else {
            String nisn = txtNisn.getText().trim();
            String nama = txtNama.getText().trim();
            String gender = rbL.isSelected() ? "L" : "P";
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal_lahir = txtLahir.getDate() != null ? dateFormat.format(txtLahir.getDate()) : "";
            String kelas = String.valueOf(spnKelas.getValue()).trim();
            Jurusan jurusan = null;
            for (Jurusan j : listJurusan) {
                if (j.getNama().equals(String.valueOf(comboJurusan.getSelectedItem()))) {
                    jurusan = j;
                    break;
                }
            }
            String index_jurusan = String.valueOf(spnIndexJurusan.getValue()).trim();
            String email = txtEmail.getText().trim();
            
            if (nisn.isEmpty() || nama.isEmpty() || gender.isEmpty() || tanggal_lahir.isEmpty() || email.isEmpty() || kelas.isEmpty() || jurusan == null || index_jurusan.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tidak boleh ada inputan yang kosong");
                return;
            }
            
            try {
                KesequlHttpRequest req = new KesequlHttpRequest(KesequlHttpRequest.Method.POST);
                req.setUrl("siswa/editsiswa?token=" + user.getToken());

                UrlEncodedFormEntity form = new UrlEncodedFormEntity(
                    Arrays.asList(
                        new BasicNameValuePair("id_user", String.valueOf(editEntity.getUser().getIdUser())),
                        new BasicNameValuePair("nisn", nisn),
                        new BasicNameValuePair("nama", nama),
                        new BasicNameValuePair("gender", gender),
                        new BasicNameValuePair("tanggal_lahir", tanggal_lahir),
                        new BasicNameValuePair("email", email),
                        new BasicNameValuePair("kelas", kelas),
                        new BasicNameValuePair("id_jurusan", String.valueOf(jurusan.getIdJurusan())),
                        new BasicNameValuePair("index_jurusan", index_jurusan)
                    )
                );
                
                Client.executeForResult(true, form, req, null, new KesequlHttpCallback() {
                    @Override
                    public void onPrepare() {
                        btnEdit.setEnabled(false);
                    }
                    
                    @Override
                    public void onSuccess(int status, String pesan, Object data) {
                        if (!Client.isTokenExpired(KelolaSiswa.this, status, user)) {
                            if (status == 1) {
                                editMode = false;
                                editEntity = null;

                                txtNisn.setText("");
                                txtNama.setText("");
                                rbL.setSelected(true);
                                txtLahir.setDate(null);
                                txtEmail.setText("");
                                spnKelas.setValue(10);
                                spnIndexJurusan.setValue(1);
                            }
                            JOptionPane.showMessageDialog(KelolaSiswa.this, pesan);
                        }
                    }

                    @Override
                    public void onFailed(Exception ex) {
                        JOptionPane.showMessageDialog(KelolaSiswa.this, ex.getMessage());
                    }

                    @Override
                    public void onDone() {
                        btnRefresh.setEnabled(!editMode);
                        btnBan.setEnabled(!editMode);
                        btnTambah.setEnabled(!editMode);
                        btnEdit.setText(!editMode ? "Edit" : "Terapkan");
                        btnEdit.setEnabled(true);
                        btnHapus.setEnabled(!editMode);

                        btnRefreshActionPerformed(evt);
                    }
                });
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        btnRefresh.setEnabled(!editMode);
        btnBan.setEnabled(!editMode);
        btnTambah.setEnabled(!editMode);
        btnEdit.setText(!editMode ? "Edit" : "Terapkan");
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(!editMode);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = table.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Mau Diedit");
            return;
        }

        Siswa siswaS = listSiswa.get(row);
        
        if (JOptionPane.showConfirmDialog(this, "Yakin ingin dihapus ?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            try {
                KesequlHttpRequest req = new KesequlHttpRequest(KesequlHttpRequest.Method.POST);
                req.setUrl("siswa/hapussiswa?token=" + user.getToken());
                
                UrlEncodedFormEntity form = new UrlEncodedFormEntity(
                    Arrays.asList(
                        new BasicNameValuePair("id_user", String.valueOf(siswaS.getUser().getIdUser()))
                    )
                );
                
                Client.executeForResult(true, form, req, null, new KesequlHttpCallback() {
                    @Override
                    public void onPrepare() {
                        btnHapus.setEnabled(false);
                    }
                    
                    @Override
                    public void onSuccess(int status, String pesan, Object data) {
                        if (!Client.isTokenExpired(KelolaSiswa.this, status, user))
                            JOptionPane.showMessageDialog(KelolaSiswa.this, pesan);
                    }

                    @Override
                    public void onFailed(Exception ex) {
                        JOptionPane.showMessageDialog(KelolaSiswa.this, ex.getMessage());
                    }

                    @Override
                    public void onDone() {
                        btnHapus.setEnabled(true);
                        btnRefreshActionPerformed(evt);
                    }
                });
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanActionPerformed
        int row = table.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Mau Diedit");
            return;
        }

        Siswa siswaS = listSiswa.get(row);
        
        String reason = JOptionPane.showInputDialog(this, "Masukan Alasan Ban");
        if (reason != null) {
            try {
                KesequlHttpRequest req = new KesequlHttpRequest(KesequlHttpRequest.Method.POST);
                req.setUrl("user/ban?token=" + user.getToken());

                UrlEncodedFormEntity form = new UrlEncodedFormEntity(
                        Arrays.asList(
                            new BasicNameValuePair("id_user", String.valueOf(siswaS.getUser().getIdUser())),
                            new BasicNameValuePair("reason_ban", reason)
                        )
                    );
                
                Client.executeForResult(true, form, req, null, new KesequlHttpCallback() {
                    @Override
                    public void onPrepare() {
                        btnBan.setEnabled(false);
                    }
                    
                    @Override
                    public void onSuccess(int status, String pesan, Object data) {
                        if (!Client.isTokenExpired(KelolaSiswa.this, status, user))
                            JOptionPane.showMessageDialog(KelolaSiswa.this, pesan);
                    }

                    @Override
                    public void onFailed(Exception ex) {
                        JOptionPane.showMessageDialog(KelolaSiswa.this, ex.getMessage());
                    }

                    @Override
                    public void onDone() {
                        btnBan.setEnabled(true);
                        btnRefreshActionPerformed(evt);
                    }
                });
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnBanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (chooserImage.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooserImage.getSelectedFile();
            
            txtGambar.setText(file.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBan;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JFileChooser chooserImage;
    private javax.swing.JComboBox<String> comboJurusan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbL;
    private javax.swing.JRadioButton rbP;
    private javax.swing.ButtonGroup rb_jk;
    private javax.swing.JSpinner spnIndexJurusan;
    private javax.swing.JSpinner spnKelas;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGambar;
    private com.toedter.calendar.JDateChooser txtLahir;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNisn;
    // End of variables declaration//GEN-END:variables
}
